---
- name: Harden server
  hosts: demo
  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
  vars:
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding
      net.ipv4.ip_forward: 1
    os_auth_pw_max_age: 99999
    sftp_enabled: true
    ssh_server_ports:
      - "22"
    ssh_permit_root_login: "no"

- name: Install Docker
  hosts: demo
  roles:
    - geerlingguy.docker
  vars:
    docker_edition: "ce"
    docker_compose_version: "1.28.4"

- name: Install node_exporter
  hosts: demo
  roles:
    - geerlingguy.node_exporter
