---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 8.6.0
  - name: devsec.hardening
    version: 9.0.1

roles:
  - name: geerlingguy.docker
    version: 7.1.0
  - name: geerlingguy.node_exporter
    version: 2.1.0
